name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get htcpp revision
        id: htcpp-version
        run: |
          revision=$(grep '^FROM htcpp:' Dockerfile | cut -d':' -f2)
          echo "revision=$revision" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Try to restore htcpp image from cache
      - name: Cache Docker htcpp image
        id: cache-htcpp
        uses: actions/cache@v4
        with:
          path: /tmp/htcpp-image.tar
          key: htcpp-${{ steps.htcpp-version.outputs.revision }}

      # Load cached image if it exists
      - name: Load cached htcpp image
        if: steps.cache-htcpp.outputs.cache-hit == 'true'
        run: |
          docker load < /tmp/htcpp-image.tar
          echo "Found htcpp image in cache"

      # Only checkout and build htcpp if not found in cache
      - name: Checkout htcpp
        if: steps.cache-htcpp.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: pfirsich/htcpp
          path: htcpp
          ref: ${{ steps.htcpp-version.outputs.revision }}

      - name: Build htcpp image
        if: steps.cache-htcpp.outputs.cache-hit != 'true'
        run: |
          cd htcpp
          docker build -t htcpp:${{ steps.htcpp-version.outputs.revision }} .
          docker save htcpp:${{ steps.htcpp-version.outputs.revision }} > /tmp/htcpp-image.tar
          cd ..

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install raydor
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/pfirsich/raydor.git

      - name: Generate output with raydor
        run: raydor --output output raydor.yml

      - name: Build application image
        run: docker build --tag theshoemaker .

      - name: Save Docker image
        run: docker save theshoemaker:latest | gzip > theshoemaker.tar.gz

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp theshoemaker.tar.gz root@${{ vars.DEPLOY_HOST }}:/root
          ssh root@${{ vars.DEPLOY_HOST }} "gunzip -f theshoemaker.tar.gz"
          ssh root@${{ vars.DEPLOY_HOST }} "docker load --input theshoemaker.tar"
          ssh root@${{ vars.DEPLOY_HOST }} "rm theshoemaker.tar"
          ssh root@${{ vars.DEPLOY_HOST }} "docker stop theshoemaker || true"
          ssh root@${{ vars.DEPLOY_HOST }} "docker rm --force theshoemaker || true"
          ssh root@${{ vars.DEPLOY_HOST }} "docker run \
            --detach \
            --init \
            --name theshoemaker \
            --network=host \
            --restart=unless-stopped \
            --volume /htcpp_data:/root/.local/share/htcpp \
            theshoemaker"
