name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get htcpp revision
        id: htcpp-version
        run: |
          revision=$(grep '^FROM htcpp:' Dockerfile | cut -d':' -f2)
          echo "revision=$revision" >> $GITHUB_OUTPUT

      - name: Checkout htcpp
        uses: actions/checkout@v4
        with:
          repository: pfirsich/htcpp
          path: htcpp
          ref: ${{ steps.htcpp-version.outputs.revision }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install raydor
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/pfirsich/raydor.git

      - name: Build htcpp image
        run: |
          cd htcpp
          docker build -t htcpp:${{ steps.htcpp-version.outputs.revision }} .
          cd ..

      - name: Generate output with raydor
        run: raydor --output output raydor.yml

      - name: Build application image
        run: docker build --tag theshoemaker .

      - name: Save Docker image
        run: docker save theshoemaker:latest | gzip > theshoemaker.tar.gz

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp theshoemaker.tar.gz ${{ vars.DEPLOY_HOST }}:/root
          ssh ${{ vars.DEPLOY_HOST }} "gunzip -f theshoemaker.tar.gz"
          ssh ${{ vars.DEPLOY_HOST }} "docker load --input theshoemaker.tar"
          ssh ${{ vars.DEPLOY_HOST }} "docker stop theshoemaker || true"
          ssh ${{ vars.DEPLOY_HOST }} "docker rm --force theshoemaker || true"
          ssh ${{ vars.DEPLOY_HOST }} "docker run \
            --detach \
            --init \
            --name theshoemaker \
            --network=host \
            --restart=unless-stopped \
            --volume /htcpp_data:/root/.local/share/htcpp \
            theshoemaker"
